"""Add attributes to Movie

Revision ID: 2e10add037ae
Revises: 3254bc09e79b
Create Date: 2025-03-18 12:55:38.955616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e10add037ae'
down_revision: Union[str, None] = '3254bc09e79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('regia', sa.String(), nullable=False))
    op.add_column('movies', sa.Column('genere', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'genere')
    op.drop_column('movies', 'regia')
    # ### end Alembic commands ###
